### ISSUE TITLE
是否开源

### ISSUE THREAD

**Issue by torns** [Senparc/NeuChar-App-Sample#1]
请问以后考虑开源吗?

**Comment by JeffreySu** [comment]
Senparc.NeuChar.dll 已经开源了：https://github.com/Senparc/NeuChar ，以后还会开放更多项目

**Comment by JeffreySu** [comment]
新版本已升级至 .NET 7.0，项目将重新启动，并结合 AI 等一系列能力，欢迎关注 😄
